# Generated by Django 2.2.9 on 2020-02-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='ana',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
